# Generated by Django 5.0.2 on 2026-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dietrestriction_foodallergy_medicalcondition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'amount']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='accent_color',
            field=models.CharField(default='emerald', help_text='Tailwind color: emerald, teal, indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_label',
            field=models.CharField(blank=True, help_text='e.g. FREE, PREMIUM, ANNUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='Subscription duration in days'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features. Prefix with x: to mark unavailable'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark as free tier'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Show Most Popular badge'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='savings_text',
            field=models.CharField(blank=True, help_text='e.g. Save 1089', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order (lower first)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Subscription fee (0 for free)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, help_text='Short tagline shown below price'),
        ),
    ]
