# Generated by Django 5.0.2 on 2026-03-29 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_registrationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure & Servers'), ('Marketing', 'Marketing & Ads'), ('Operations', 'Operations & Salaries'), ('Software', 'Software Licenses'), ('Other', 'Miscellaneous')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('User', 'User'), ('FoodItem', 'Food Item'), ('ConsumptionLog', 'Consumption Log'), ('Transaction', 'Transaction'), ('Expense', 'Expense')], max_length=50)),
                ('original_id', models.IntegerField()),
                ('details', models.TextField(help_text='JSON or string details of the deleted item')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deleted_records',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('is_favorite', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fooditem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='api.userprofile')),
            ],
            options={
                'db_table': 'food_preferences',
                'unique_together': {('user_profile', 'food_item', 'meal_type', 'day_of_week')},
            },
        ),
    ]
