# Generated by Django 5.0.2 on 2026-03-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminexpense_deletedrecord_foodpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='foodpreference',
            name='food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodpreference',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fooditem'),
        ),
        migrations.AlterUniqueTogether(
            name='foodpreference',
            unique_together={('user_profile', 'food_name', 'meal_type', 'day_of_week')},
        ),
    ]
